language: php
php:
- 5.6
- 5.5
- 7.0
install:
- composer install
env:
  global:
    - APP_ENV=testing
    - APP_KEY=M0HYKpEoPSPnl7V4Ck6notarealkeyUx
    - TWILIO_ACCOUNT_SID=my-account-sid
    - TWILIO_AUTH_TOKEN=my-auth-token
    - TWILIO_PHONE_NUMBER=+14155551213
  before_install:
    - cp .env.example .env
    - php TouchDatabase.php
  before_script:
    - php artisan migrate
    - php artisan db:seed
